### ISSUE TITLE
cordova 9 installation failes

### ISSUE THREAD

**Issue by nerumo** [transistorsoft/cordova-plugin-cocoalumberjack#1]
With the cordova 9 (latest nightly build) the installation of the plugin failes with:

```
Installing "cordova-plugin-cocoalumberjack" for ios
(node:5404) UnhandledPromiseRejectionWarning: TypeError: doc.find is not a function
    at Object.resolveParent (C:\Users\MarcoBachmann\AppData\Local\Yarn\Data\global\node_modules\cordova-common\src\util\xml-helpers.js:207:26)
    at C:\Users\MarcoBachmann\AppData\Local\Yarn\Data\global\node_modules\cordova-common\src\ConfigChanges\ConfigChanges.js:345:53
    at Array.forEach (<anonymous>)
    at is_conflicting (C:\Users\MarcoBachmann\AppData\Local\Yarn\Data\global\node_modules\cordova-common\src\ConfigChanges\ConfigChanges.js:337:17)
    at PlatformMunger.add_config_changes (C:\Users\MarcoBachmann\AppData\Local\Yarn\Data\global\node_modules\cordova-common\src\ConfigChanges\ConfigChanges.js:188:33)
    at C:\Users\MarcoBachmann\AppData\Local\Yarn\Data\global\node_modules\cordova-lib\src\cordova\prepare.js:130:32
    at _fulfilled (C:\dev\riwax\client\apps\mobile\platforms\ios\cordova\node_modules\q\q.js:854:54)
    at self.promiseDispatch.done (C:\dev\riwax\client\apps\mobile\platforms\ios\cordova\node_modules\q\q.js:883:30)
    at Promise.promise.promiseDispatch (C:\dev\riwax\client\apps\mobile\platforms\ios\cordova\node_modules\q\q.js:816:13)
    at C:\dev\riwax\client\apps\mobile\platforms\ios\cordova\node_modules\q\q.js:624:44
(node:5404) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```

**Comment by christocracy** [comment]
No idea.

**Comment by christocracy** [comment]
Does this come from using my [cordova-background-geolocation-lt](https://github.com/transistorsoft/cordova-background-geolocation-lt)?

**Comment by nerumo** [comment]
yes...it comes as a dependency

**Comment by christocracy** [comment]
Are you trying it in a fresh new "Hello World"?

**Comment by nerumo** [comment]
I tested again with the final version of cordova 9.0.0 and it works now. Sorry for the noise
